"""fhir-mcp: an MCP server exposing a FHIR server as tools.

Part of AgentWard. All data behind this server is synthetic, generated by
Synthea. Nothing produced here is clinical advice or validated for clinical
use.
"""

__version__ = "0.1.0"
