"""The fhir-mcp server: wiring, lifespan, and entry point.

Run it directly:

    uv run python -m fhir_mcp.server

For interactive poking, point the MCP Inspector at the running server rather
than using `mcp dev` (that command imports this file as a standalone script,
so its relative imports fail, and it would spawn a second, stdio-wrapped
server rather than attach to this one). See the README's "For interactive
poking" section.
"""

from __future__ import annotations

import logging
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager

from mcp.server import CacheHint, MCPServer
from mcp.server.transport_security import TransportSecuritySettings
from starlette.requests import Request
from starlette.responses import JSONResponse, Response

from . import tools_level1
from .config import Settings
from .fhir_client import FhirClient
from .tools_level1 import AppContext

# Logging goes to stderr. The 2026-07-28 specification deprecated MCP's own
# logging feature, and its suggested replacement is stderr or OpenTelemetry.
# Under stdio transport, stdout carries protocol messages, so anything printed
# there corrupts the stream. stderr is safe under every transport.
logger = logging.getLogger("fhir_mcp")


def build_server(settings: Settings | None = None) -> MCPServer:
    """Construct the MCP server with its tools and lifespan attached.

    Separated from `main` so tests can build a server without running one.

    Args:
        settings: Configuration to use. Read from the environment when omitted.
    """
    settings = settings or Settings.from_env()

    @asynccontextmanager
    async def lifespan(server: MCPServer) -> AsyncIterator[AppContext]:
        """Open one FHIR client for the life of the process.

        A client per request would discard connection pooling. Over a 15-step
        agent loop that is a measurable cost for no benefit.
        """
        logger.info(
            "fhir-mcp starting, fhir_base_url=%s serialisation=%s",
            settings.fhir_base_url,
            settings.serialisation,
        )
        client = FhirClient(
            base_url=settings.fhir_base_url,
            timeout_seconds=settings.request_timeout_seconds,
        )
        try:
            yield AppContext(fhir=client, settings=settings)
        finally:
            # Runs on shutdown and on startup failure, so the pool is never
            # left dangling.
            await client.close()
            logger.info("fhir-mcp stopped")

    mcp = MCPServer(
        name="fhir-mcp",
        title="FHIR tools for AgentWard",
        version="0.1.0",
        instructions=(
            "Read-only access to a FHIR server holding synthetic patient records. "
            "All data is synthetic and generated by Synthea. Nothing here is real "
            "patient data, and nothing produced from it is clinical advice or "
            "validated for clinical use.\n\n"
            "These are thin tools over the FHIR REST API: one resource type per "
            "search, no joins across types, no filtering the FHIR search "
            "parameters cannot express. Questions that span resource types take "
            "several calls plus reasoning over the results.\n\n"
            "When reporting a finding, cite the FHIR references that support it "
            "rather than restating resource contents as prose."
        ),
        lifespan=lifespan,
        # Caching hints from the 2026-07-28 specification. The tool list is
        # prefill tokens on every model call in the loop, so letting clients
        # cache it for five minutes is a direct saving on every step.
        # "public" is correct here because the list does not vary by caller:
        # these tools carry no per-user authorisation.
        cache_hints={"tools/list": CacheHint(ttl_ms=300_000, scope="public")},
    )

    tools_level1.register(mcp, settings)

    @mcp.custom_route("/healthz", methods=["GET"])
    async def healthz(request: Request) -> Response:
        """Liveness only: the process is up and serving. Not a dependency
        check, this container has no meaningful degraded state to report if
        HAPI FHIR is unreachable, every tool call already surfaces that per
        request through the normal FhirError -> ToolError path.
        """
        return JSONResponse({"status": "ok"})

    return mcp


def main() -> None:
    """Entry point: build the server and serve it over streamable HTTP."""
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s %(message)s",
    )

    settings = Settings.from_env()
    mcp = build_server(settings)

    # Streamable HTTP rather than stdio: the substrate is already a set of
    # Docker services, and the published MCP roadmap is converging on
    # streamable HTTP as the single transport.
    #
    # stateless_http=True matters and is not the SDK's default. The manager
    # routes a request to the true 2026-07-28 handler only when the caller
    # sends an `Mcp-Protocol-Version` header the SDK recognises as modern; a
    # request with no such header (found by testing this server with plain
    # curl rather than the SDK's own client, which sends it invisibly) falls
    # back to legacy transport logic, which without this flag demands an
    # `Mcp-Session-Id` and rejects anything else with a bare "Missing session
    # ID". That is exactly the stateful behaviour our own project brief
    # targets moving away from, so it should not be the fallback for a client
    # that simply did not ask for it either way.
    mcp.run(
        transport="streamable-http",
        host=settings.host,
        port=settings.port,
        stateless_http=True,
        # The SDK's own default DNS-rebinding protection only allows Host
        # headers of 127.0.0.1/localhost/[::1]. Passing our own
        # TransportSecuritySettings replaces that default rather than
        # extending it, so settings.allowed_hosts (config.py) repeats those
        # plus whatever else this deployment needs, e.g. "fhir-mcp:*" for a
        # sibling container reaching this one by its docker-compose service
        # name. Origin is not widened the same way: it's only sent by
        # browser-originated requests, none of which are expected here, and
        # an absent Origin header already passes (see _validate_origin).
        transport_security=TransportSecuritySettings(
            allowed_hosts=list(settings.allowed_hosts),
            allowed_origins=[
                "http://127.0.0.1:*",
                "http://localhost:*",
                "http://[::1]:*",
            ],
        ),
    )


if __name__ == "__main__":
    main()
